version: '3.8'

services:
  flyway-products:
    image: flyway/flyway:latest
    container_name: flyway_products
    entrypoint: ["sh", "-c", "tail -f /dev/null"]
    environment:
      - FLYWAY_SCHEMAS=products
      - FLYWAY_TABLE=flyway_products_history
    # command: migrate tail -f /dev/null
    volumes:
      - ${WORKSPACE}/flyway/sql/products:/flyway/sql
      - ${WORKSPACE}/conf:/flyway/conf
  flyway-public:
    image: flyway/flyway:latest
    container_name: flyway_public
    entrypoint: ["sh", "-c", "tail -f /dev/null"]
    environment:
      - FLYWAY_SCHEMAS=public
      - FLYWAY_TABLE=flyway_public_history
    # command: migrate tail -f /dev/null
    volumes:
      - ${WORKSPACE}/flyway/sql/public:/flyway/sql    
      - ${WORKSPACE}/conf:/flyway/conf