version: '3.8'

services:
  flyway-products:
    image: flyway/flyway:latest
    container_name: flyway_products
    environment:
      - FLYWAY_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=admin@123
      - FLYWAY_SCHEMAS=products
      - FLYWAY_TABLE=flyway_products_history
    command: migrate
    volumes:
      - ./flyway/sql/products:/flyway/sql
  flyway-public:
    image: flyway/flyway:latest
    container_name: flyway_public
    environment:
      - FLYWAY_URL=jdbc:postgresql://host.docker.internal:5432/postgres
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=admin@123
      - FLYWAY_SCHEMAS=public
      - FLYWAY_TABLE=flyway_public_history
    command: migrate
    volumes:
      - ./flyway/sql/public:/flyway/sql    