version: '3.8'

services:
  flyway-products:
    image: flyway/flyway:latest
    container_name: flyway_products
    environment:
      - FLYWAY_SCHEMAS=products
      - FLYWAY_TABLE=flyway_products_history
    command: migrate
    volumes:
      - ./flyway/sql/products:/flyway/sql
      - ./conf:/flyway/conf
  flyway-public:
    image: flyway/flyway:latest
    container_name: flyway_public
    environment:
      - FLYWAY_SCHEMAS=public
      - FLYWAY_TABLE=flyway_public_history
    command: migrate
    volumes:
      - ./flyway/sql/public:/flyway/sql    
      - ./conf:/flyway/conf