version: '3.8'

services:
  flyway-products:
    image: flyway/flyway:latest
    container_name: flyway_products
    environment:
      - FLYWAY_SCHEMAS=products
      - FLYWAY_TABLE=flyway_products_history
      - FLYWAY_LOCATIONS=filesystem:/mnt/${FLYWAY_WORKDIR}/flyway/sql/products
    command: -url=${FLYWAY_DB_URL} -user=${FLYWAY_DB_USERNAME} -password=${FLYWAY_DB_PASSWORD} migrate
    volumes:
      - jenkins-workspaces:/mnt
  flyway-public:
    image: flyway/flyway:latest
    container_name: flyway_public
    environment:
      - FLYWAY_SCHEMAS=public
      - FLYWAY_TABLE=flyway_public_history
      - FLYWAY_LOCATIONS=filesystem:/mnt/${FLYWAY_WORKDIR}/flyway/sql/public
    command: -url=${FLYWAY_DB_URL} -user=${FLYWAY_DB_USERNAME} -password=${FLYWAY_DB_PASSWORD} migrate
    volumes:
      - jenkins-workspaces:/mnt

volumes:
  jenkins-workspaces:
    external: true
    name: jenkins-workspaces