version: '3.8'

services:
  flyway-products:
    image: flyway/flyway:latest
    container_name: flyway_products
    environment:
      - FLYWAY_SCHEMAS=products
      - FLYWAY_TABLE=flyway_products_history
      - FLYWAY_LOCATIONS=filesystem:/mnt/${FLYWAY_WORKDIR}/flyway/sql/products
      - FLYWAY_CONFIG_FILES=/mnt/${FLYWAY_WORKDIR}/conf/flyway.conf
    command: migrate
    volumes:
      - jenkins-workspaces:/mnt
  flyway-public:
    image: flyway/flyway:latest
    container_name: flyway_public
    environment:
      - FLYWAY_SCHEMAS=public
      - FLYWAY_TABLE=flyway_public_history
      - FLYWAY_LOCATIONS=filesystem:/mnt/${FLYWAY_WORKDIR}/flyway/sql/public
      - FLYWAY_CONFIG_FILES=/mnt/${FLYWAY_WORKDIR}/conf/flyway.conf
    command: migrate
    volumes:
      - jenkins-workspaces:/mnt

volumes:
  jenkins-workspaces:
    external: true
    name: jenkins-workspaces